### ISSUE TITLE
[バグ]チャンネル登録時にエラーが発生することについて

### ISSUE THREAD

**Issue by shalupe** [Hayao-H/Niconicome#146]
Niconicomeスレの>>12,13です。
以下にログを張っておきます。

Niconicomeログ
App Version : 0.3.0.21416
App Path : D:\個人情報保護のため省略します(日本語のファイル名でした)\Niconicome\Niconicome.exe
OS : Windows 10
OS Version : Microsoft Windows NT 10.0.18363.0
Date : 21/03/30 0:48:10
---------------------------------------------------

[00:48.10][Error] チャンネルページの取得に失敗しました。
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 404 (Not Found).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Video.Channel.ChannelVideoHandler.GetChannelPage(String channelId)
---------------------------------------------------

[00:49.19][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so21796555)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[00:49.29][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so21856690)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[00:49.29][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so21905805)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

**Comment by shalupe** [comment]
すみません
タイトルが「エラー登録時」になっていました。正しくは、「チャンネル登録時」です。
ご迷惑をかけてしまい、申し訳ございませんでした。

**Comment by Hayao-H** [comment]
ご報告ありがとうございます
