### ISSUE TITLE
[バグ]チャンネル取得に失敗する

### ISSUE THREAD

**Issue by shalupe** [Hayao-H/Niconicome#153]
昨日、チャンネル取得のバグ報告をさせていただいた者です。
重ね重ねの報告で申し訳ないのですが、当方では問題が解決していなかったため
もう一度ログを張らせていただきます。
御足労をかける様で申し訳ないですが、問題解決よろしくお願い致します。

Niconicomeログ
App Version : 0.3.2.7476
App Path : D:\省略\Niconicome\Niconicome.exe
OS : Windows 10
OS Version : Microsoft Windows NT 10.0.18363.0
Date : 21/03/30 13:46:05
---------------------------------------------------

[13:46.05][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so23641109)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[13:46.05][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so23589925)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[13:46.05][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so23384584)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[13:46.20][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so23692010)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[13:46.20][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so23748640)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[13:46.20][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so23538168)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[13:46.20][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so23399195)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[13:46.20][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so23792397)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

[13:46.35][Error] 動画情報の取得に失敗しました(url: https://nicovideo.jp/watch/so23850335)
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Response status code does not indicate success: 429 (Too Many Requests).
Exception Type : HttpRequestException
Stack Trace :
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Niconicome.Models.Domain.Niconico.NicoHttp.GetStringAsync(Uri uri)
   at Niconicome.Models.Domain.Niconico.Watch.WatchInfohandler.GetVideoInfoAsync(String id, WatchInfoOptions options)
---------------------------------------------------

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
設定＞＞一般設定＞＞「動画情報取得時の並列取得数」を1に、「動画情報取得時の待機間隔」を3またはそれより小さい値にしてお試しください。
可能であれば結果のご報告をお願いいたします。

**Comment by shalupe** [comment]
今、「ごちうさ」と「きんモザ」の両方でテストをしてみたのですが、「動画情報取得時の待機間隔」は2以上を選択するとだと必ず失敗し、「動画情報取得時の並列取得数」は3以上を選択すると失敗してしまいました。
ですが、「動画情報取得時の並列取得数」を2以下、「動画情報取得時の待機間隔」を1に設定したら問題なくチャンネル取得ができました。

追記：使用しているアカウントは一般会員アカウントです。

**Comment by Hayao-H** [comment]
ありがとうございます。
チャンネル動画情報の取得ではすべての動画で視聴ページにアクセスして情報を取得する、所謂スクレイピングを行っているのですが、
ニコニコには一般アカウントによる同時アクセスを制限する謎使用（サーバー保護の為？）があるので、おそらくそれに引っかかったものと思われます。

**Comment by shalupe** [comment]
対応ありがとうございました。
こちらのアカウントが原因であったのに、時間を取らせてしまい申し訳ございませんでした。

**Comment by Hayao-H** [comment]
解決して良かったです。
また何か問題が発生するようであれば、もう一度新たにIssueを立ててください。
よろしくお願いします。
