### ISSUE TITLE
[バグ] コメント数が多い動画でコメントの取得に失敗する(status_code:429, reason_phrase:Too Many Requests)

### ISSUE THREAD

**Issue by RenardNotes** [Hayao-H/Niconicome#426]
**バグの説明**
コメント数が多い動画でコメントの取得に失敗する

**再現方法**
古い動画かつコメント数が1万を超えていると高確率で失敗しているように見える
(1部ダウンロードできるものもあり)

* 成功
  * [コメント数: 9,218](https://www.nicovideo.jp/watch/sm36506265) → 成功
  * [コメント数: 12,848](https://www.nicovideo.jp/watch/sm14257396) → 成功
  * [コメント数: 22,770](https://www.nicovideo.jp/watch/sm19577010) → 成功

* 失敗
  * [コメント数: 10,843](nicovideo.jp/watch/sm29188224) → 失敗
  * [コメント数: 1,009,042](https://www.nicovideo.jp/watch/sm1715919) → 失敗

**期待する挙動**
コメントをダウンロードできる

**スクリーンショット**
なし

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows 10 Pro 64bit 
 - OSビルド: 19042.1237
 - Version: 0.9.0.23410

**ログファイル**
```
[04:20.57][Error] コメントの取得に失敗しました。
Niconicomeエラー情報
---------------------------------------------------
Exception Message : コメントの取得に失敗しました。(status_code:429, reason_phrase:Too Many Requests)
Exception Type : HttpRequestException
Stack Trace :
   at Niconicome.Models.Domain.Niconico.Download.Comment.CommentClient.GetCommentsAsync(IDmcInfo dmcInfo, ICommentDownloadSettings settings, Nullable`1 when)
   at Niconicome.Models.Domain.Niconico.Download.Comment.CommentClient.DownloadCommentAsync(IDmcInfo dmcInfo, ICommentDownloadSettings settings, IDownloadMessenger messenger, IDownloadContext context, CancellationToken token)
   at Niconicome.Models.Domain.Niconico.Download.Comment.CommentDownloader.DownloadComment(IWatchSession session, ICommentDownloadSettings settings, Action`1 onMessage, IDownloadContext context, CancellationToken token)
---------------------------------------------------
```

**備考**
すばらしいOSSありがとうございます。
C#は全く分からないためコントリビュートはできませんが、今後も陰ながら開発の方を応援しています。

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
過去ログ取得時に待機処理を入れていないため、リクエスト過多によるサーバーエラーが発生しているようです。
修正します。

**Comment by RenardNotes** [comment]
@Hayao-H 
素早い修正ありがとうございます。
v0.10.0で再びダウンロードしてみたところ、変わらずコメントの取得に失敗していました。
表面上の原因は特定できましたので[#428](https://github.com/Hayao-H/Niconicome/pull/428#discussion_r719668456)の方でコメントさせていただきました。
ご確認よろしくお願いいたします。
