### ISSUE TITLE
[バグ] プレミアムアカウントでの自動アカウントのログインができないずエラーウィンドウを吐いた後に強制終了する

### ISSUE THREAD

**Issue by Ugya** [Hayao-H/Niconicome#495]
**バグの説明**
v0.9.0よりv0.11.0に上書き後、.NET6インストール及びPageAnalyzePluginのv1.3.0へのアップデート、アプリ側要求によるアプリリセット
niconicome自体は起動するが、プレミアムアカウントでのログインできず(保存済cookieでのログイン、ログインウィンドウを呼び出してID/パスワード等を入力してのログインも同じ)
≡よりログイン操作をすると見た目上はログインしているように見えるが、ファイルIDを利用してプレイリストに登録しようとすると強制終了する

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
自動ログインの要不要は別としてログインが出来、プレイリストの追加、ファイル等のダウンロードが出来ること

**スクリーンショット**
https://i.imgur.com/pstH0Gp.jpeg

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows 11 Pro / 21H2 22000.613
 - Version: v0.11.0 x64  / PageAnalyzePlugin v1.3.0

**ログファイル**
Niconicomeログ
App Version : 0.11.0.12706
App Path : D:\ProgramFiles(Non_Systems)\ツール\niconicome\Niconicome.exe
OS : Windows 10
OS Version : Microsoft Windows NT 10.0.22000.0
OS Architecture : 64bit Operating System
Process : 64bit Process
Date : 22/04/19 17:01:06
---------------------------------------------------

[17:01.06][Error] UIスレッドで例外が発生しました。
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Collection was modified; enumeration operation may not execute.
Exception Type : InvalidOperationException
Stack Trace :
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Niconicome.Models.Network.Download.DownloadTaskPool.RemoveTasks(IEnumerable`1 tasks)
   at Niconicome.Models.Network.Download.DownloadTasksHandler.RemoveStaged(IEnumerable`1 tasks)
   at Niconicome.Models.Network.Download.DownloadTasksHandler.MoveStagedToQueue(Func`2 predicate, Boolean clearAfterMove)
   at Niconicome.ViewModels.Mainpage.DownloadSettingsViewModel.DownloadVideo(VideoInfoViewModel vm)
   at Niconicome.ViewModels.Mainpage.DownloadSettingsViewModel.<.ctor>b__0_25()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------------------------------

[17:01.13][Error] UIスレッドで例外が発生しました。
Niconicomeエラー情報
---------------------------------------------------
Exception Message : Collection was modified; enumeration operation may not execute.
Exception Type : InvalidOperationException
Stack Trace :
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Niconicome.Models.Network.Download.DownloadTaskPool.RemoveTasks(IEnumerable`1 tasks)
   at Niconicome.Models.Network.Download.DownloadTasksHandler.RemoveStaged(IEnumerable`1 tasks)
   at Niconicome.Models.Network.Download.DownloadTasksHandler.MoveStagedToQueue(Func`2 predicate, Boolean clearAfterMove)
   at Niconicome.ViewModels.Mainpage.DownloadSettingsViewModel.DownloadVideo(VideoInfoViewModel vm)
   at Niconicome.ViewModels.Mainpage.DownloadSettingsViewModel.<.ctor>b__0_25()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------------------------------

Niconicomeログ
App Version : 0.11.0.12706
App Path : D:\ProgramFiles(Non_Systems)\ツール\niconicome\Niconicome.exe
OS : Windows 10
OS Version : Microsoft Windows NT 10.0.22000.0
OS Architecture : 64bit Operating System
Process : 64bit Process
Date : 22/04/19 17:01:50
---------------------------------------------------

[17:01.50][Error]プレイリストの取得に失敗しました。
[17:01.50][Log]プレイリスト(name:プレイリスト一覧, ID:2)を更新しました。
[17:01.50][Log]プレイリスト(name:プレイリスト一覧, ID:2)を取得しました。
[17:01.50][Log]プレイリスト(name:新しいプレイリスト, ID:7)を更新しました。
[17:01.50][Error]プレイリストの取得に失敗しました。
[17:01.50][Log]プレイリスト(name:最近ダウンロードした動画, ID:8)を更新しました。
[17:01.50][Error]プレイリストの取得に失敗しました。
[17:01.50][Log]プレイリスト(name:最近ダウンロードに失敗した動画, ID:9)を更新しました。
[17:01.50][Error]プレイリストの取得に失敗しました。
[17:01.50][Log]プレイリスト(name:一時プレイリスト, ID:10)を更新しました。
[17:01.50][Log]プレイリスト(name:プレイリスト一覧, ID:2)を取得しました。
[17:01.50][Log]プレイリスト(name:新しいプレイリスト, ID:11)を更新しました。

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。
