### ISSUE TITLE
[バグ] There was an error generating the XML document ... hexadecimal value 0x10, is an invalid character.

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#630]
**バグの説明**
so42691575をDLしようとしたらしっぱいしました
出力では
```
[System]so42691575のダウンロード処理に失敗しました。
[System]詳細：コメントのシリアライズに失敗しました。（詳細:System.InvalidOperationException: There was an error generating the XML document.
 ---> System.ArgumentException: '', hexadecimal value 0x10, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPacketElement.Write2_ChatElement(String n, String ns, ChatElement o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPacketElement.Write3_PacketElement(String n, String ns, PacketElement o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPacketElement.Write4_packet(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at Niconicome.Models.Domain.Niconico.Net.Xml.Xmlparser.Serialize[T](T data, XmlWriterSettings settings)
   at Niconicome.Models.Domain.Niconico.Download.Comment.V2.Local.CommentWriter.WriteComment(IEnumerable`1 comments, CommentWriterOption option)）
```

`CommentWriter.cs`
の
`element.Text = Regex.Replace(element.Text, @"[\x08\x0B\x0C\x1F]", "");`
部分を
`element.Text = new String(element.Text.Where(ch => System.Xml.XmlConvert.IsXmlChar(ch)).ToArray());`
に変えたらDL成功しました。

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします): 
 - OS:  Windows 10 Pro 64 bit 21H2 19044.1645
 - Version: 0.13.3.5565

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。
