### ISSUE TITLE
[バグ]コメントはダウンロードできるけど動画がダウンロードできない

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#670]
**バグの説明**
明確な状況・バグの説明
コメントはダウンロードできるけど動画がダウンロードできない

出力
```
[System]sm34847513のダウンロード処理を開始しました。

[System]sm34847513のダウンロード処理に失敗しました。

[System]詳細：セッションの確立に失敗しました。(id:sm34847513)

[System]動画を1件もダウンロード出来ませんでした。
```

**再現方法**
検証用の動画IDでも結構です
sm34847513

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
OS: Windows 10 Pro 64bit 22H2　19045.4412
Version: 0.14.0.28768

**ログファイル**
可能であれば添付して下さい
```
    例外情報
    ---------------------------------------------------
    Exception Message : Error: https://nvapi.nicovideo.jp/v1/watch/sm34847513/access-rights/hls?actionTrackId=5ITiXtPgt7_1726830194234は許可されていないホストです。
    Exception Type : ScriptEngineException
    Stack Trace :
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke(Action`1 action)
   at Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl.InvokeWithLock(Action action)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ScriptInvoke[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptItem.InvokeMethod(Boolean marshalResult, String name, Object[] args)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass147_0.<Microsoft.ClearScript.JavaScript.IJavaScriptEngine.CreateTaskForPromise>b__1(Object error)
--- End of stack trace from previous location ---
   at CallSite.Target(Closure, CallSite, Object)
   at Niconicome.Models.Domain.Local.Addons.API.Hooks.HooksManager.EnsureSessionAsync(Object dmcInfo)
      ---------------------
      InnerException
      Exception Message : Error: https://nvapi.nicovideo.jp/v1/watch/sm34847513/access-rights/hls?actionTrackId=5ITiXtPgt7_1726830194234は許可されていないホストです。
      Exception Type : ScriptEngineException
      Stack Trace :
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke[T](Func`2 func)
   at Microsoft.ClearScript.ScriptEngine.ScriptInvokeInternal[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass137_0`1.<ScriptInvoke>b__0()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.InvokeHostAction(IntPtr pAction)
      ---------------------
        ---------------------
        InnerException
        Exception Message : Exception has been thrown by the target of an invocation.
        Exception Type : TargetInvocationException
        Stack Trace :
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.ClearScript.Util.InvokeHelpers.InvokeMethodInternal[T](IHostContext context, T method, Object target, Object[] args, Func`4 invoker, Type returnType, ScriptMemberFlags flags)
   at Microsoft.ClearScript.HostItem.InvokeHostMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.<>c__DisplayClass147_0.<InvokeReflectMember>b__0()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.InvokeHostObject(IntPtr pObject, Boolean asConstructor, Int32 argCount, Ptr pArgs, Ptr pResult)
        ---------------------
          ---------------------
          InnerException
          Exception Message : One or more errors occurred. (https://nvapi.nicovideo.jp/v1/watch/sm34847513/access-rights/hls?actionTrackId=5ITiXtPgt7_1726830194234は許可されていないホストです。)
          Exception Type : AggregateException
          Stack Trace :
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
          ---------------------
            ---------------------
            InnerException
            Exception Message : https://nvapi.nicovideo.jp/v1/watch/sm34847513/access-rights/hls?actionTrackId=5ITiXtPgt7_1726830194234は許可されていないホストです。
            Exception Type : InvalidOperationException
            Stack Trace :
   at Niconicome.Models.Local.Addon.API.Net.Http.Fetch.Fetch.FetchAsync(String url, IFetchOption option)
            ---------------------
---------------------------------------------------

[21:03.13][error][262-4]　セッションの確立に失敗しました。(id:sm34847513)
```
**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
こちら、アドオンのアップデートで解決しませんでしょうか？
アドオンマネージャー>アップデート可能なアドオンに表示されているかと思います。

**Comment by T-10001** [comment]
はい。アドオンのアップデートで解決しました。ありがとうございます。
